---
- hosts: localhost
  vars:
    - create_user_file: no
    - user: mguerrero
  tasks:
    - name: create file for user
      file:
        path: /home/{{ user }}/myfile
        state: touch
      when: create_user_file